### ISSUE TITLE
Permission to use your model for research paper

### ISSUE THREAD

**Issue by Ekanara** [MC-E/DragonDiffusion#21]
My team is about to make an Interior Design tool for Research Festival including publishing paper, and I am fascinated by your project. May I ask if I have the permission to modify this model, since the license is nowhere to be found.
I'll make sure to credit properly.

**Comment by MC-E** [comment]
Hi @Ekanara , our code is completely open-source and free to use:)

**Comment by Ekanara** [comment]
Thank you so much
