### ISSUE TITLE
Why does Figure 3 give different results in paper ？

### ISSUE THREAD

**Issue by daidaiershidi** [MC-E/DragonDiffusion#4]
Thanks for the interesting work! According Figure 2, the same noise z_{T} is passed through different branches but with the same parameters. The features obtained (no matter which layer) should also be the same, and all losses should also be a fixed value, (cos_similarity is 1). But why do different layers of features give different results?

**Comment by MC-E** [comment]
The similarity here is not a fixed value, because the features involved in the similarity calculation come from different spatial locations.

**Comment by daidaiershidi** [comment]
> The similarity here is not a fixed value, because the features involved in the similarity calculation come from different spatial locations.

I'm sorry I didn't understand. In Figure 3, you set m^{gen}, m^{gud} as zeros matrix and m^{share} as a ones matrix. In this way, why are the features involved in calculating similarity from different spatial locations?

**Comment by MC-E** [comment]
Hi, in the experiment shown in Figure 3, the input to the generation branch is random noise, while the input to the guidance branch is the inversion result. Therefore, the loss is not a fixed value.
