### ISSUE TITLE
Expected release of code time or Any tips for the reimplement of your exciting work

### ISSUE THREAD

**Issue by yangmingzhuo** [MC-E/DragonDiffusion#8]
I am really intrested in your work which can edit the photo generated by diffusion model. And I was wondering when the code will be released or any tips to reimplement your work. Thanks a lot!

**Comment by MC-E** [comment]
Thanks for your attention. Please refer to https://github.com/MC-E/DragonDiffusion/issues/2. 
This work will be open-sourced in the form of a peer-reviewed paper and attached code :)
